# AI Development Workflow Configuration Template

project:
  type: "generic"  # flutter, react, python, go, generic
  name: "sample-project"
  architecture: []  # e.g., [bloc, drift] for Flutter, [redux, hooks] for React
  
ai_tools:
  - "copilot"  # Primary AI tool
  # - "claude"   # Secondary options
  # - "gpt4"

workflows:
  story_analysis:
    enabled: true
    timeout: 120  # seconds
    outputs:
      - "docs/discovery/{epic}-{story}-discovery.md"
      - "docs/plans/{epic}-{story}-plan.md"
    
  implementation_planning:
    enabled: true
    include_testing: true
    include_architecture: true

systematic:
  enabled: true  # Enable systematic SDLC workflows
  workflows:
    project_analysis:
      enabled: true
      auto_run: false  # Run on demand
      outputs:
        - "docs/project-structure-analysis.md"
        - "docs/tech-stack-analysis.md"
        - "docs/brownfield-architecture.md"
    
    quality_checklist:
      enabled: true
      auto_generate: true  # Auto-generate checklist for each story
      interactive_mode: true
      
    document_generation:
      enabled: true
      templates_dir: "core/workflows/systematic/templates"
      output_dir: "docs"

integrations:
  vscode:
    enabled: true
    auto_open_files: true
    tasks_enabled: true
    systematic_tasks: true  # Enable systematic workflow tasks
    
  git:
    auto_branch: true
    branch_pattern: "story/{epic}-{story}-{slug}"
    auto_commit: false
    
  documentation:
    auto_generate: true
    output_format: "markdown"
    include_metadata: true
    systematic_docs: true  # Include systematic workflow documentation

# Project-specific settings (customize per project)
custom:
  prd_file: "docs/prd.md"
  discovery_dir: "docs/discovery"
  plans_dir: "docs/plans"
  scripts_dir: "scripts"
  systematic_dir: "core/workflows/systematic"